### ISSUE TITLE
npm run dev 出错

### ISSUE THREAD

**Issue by zengbiao** [imouou/buijs-cli#1]
npm -v  ==》6.1.0
node -v   ==》v10.6.0

npm run dev  

> @ dev /opt/www/p75ui
> gulp dev

fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/opt/www/p75ui/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:759:3)
    at Object.getInstalledBinaries (/opt/www/p75ui/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/opt/www/p75ui/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/opt/www/p75ui/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/opt/www/p75ui/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/opt/www/p75ui/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/opt/www/p75ui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `gulp dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-15T23_42_21_204Z-debug.log
这是啥问题？

**Comment by imouou** [comment]
node 版本可能比较低, 建议重新安装最新的node 再试
